# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fbc502a7b697403a68982a02e64f72138f840fba9258365538eba3ccd4f12d1939ba4874edd6f31abfb601e61dbbb71f56f5353b280b9abea025672ad764945

test:
  secret_key_base: b031d8961cdd851fe01828546dcef5c550172ceb04e4a1b9414a5b85dbfb3c5159d270304627ce1812c30f307adee13bd6c34ee2b44362aad2830a63740757f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
